### ISSUE TITLE
【API】代理人登録のAPIの作成

### ISSUE THREAD

**Issue by kurogenki** [sansan-event-fusion/spark-2023-teamS#10]
### 目的
- 代理人が自分の情報を登録して、購入者に住所や名前などを登録するため。

### 概要
-フロントから受け取った代理人登録用リクエストに応じて、代理人を登録するコントローラー、メソッドと紐つける。
-代理人登録用のAPIの作成
-代理人用コントローラーの作成

**Comment by Koki-Kazaore** [comment]
#22 のプルリクにて対応済み
